// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAd = "Ads"

// Ad mapped from table <Ads>
type Ad struct {
	ID        int32     `gorm:"column:id;primaryKey;default:nextval('"Ads_id_seq"" json:"id"`
	Text      string    `gorm:"column:text;not null" json:"text"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
}

// TableName Ad's table name
func (*Ad) TableName() string {
	return TableNameAd
}
