// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCasinoBet = "CasinoBet"

// CasinoBet mapped from table <CasinoBet>
type CasinoBet struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	CasinoSessionID string    `gorm:"column:casinoSessionId;not null" json:"casinoSessionId"`
	BotUserID       string    `gorm:"column:botUserId;not null" json:"botUserId"`
	Amount          int32     `gorm:"column:amount;not null" json:"amount"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt       time.Time `gorm:"column:updatedAt;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	Status          string    `gorm:"column:status;not null" json:"status"`
}

// TableName CasinoBet's table name
func (*CasinoBet) TableName() string {
	return TableNameCasinoBet
}
