// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCasinoSession = "CasinoSession"

// CasinoSession mapped from table <CasinoSession>
type CasinoSession struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	FinishedAt time.Time `gorm:"column:finishedAt;not null;default:CURRENT_TIMESTAMP" json:"finishedAt"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	Amount     int32     `gorm:"column:amount;not null" json:"amount"`
	BotUserID  string    `gorm:"column:botUserId;not null" json:"botUserId"`
	GroupID    string    `gorm:"column:groupId;not null" json:"groupId"`
	Status     string    `gorm:"column:status;not null" json:"status"`
}

// TableName CasinoSession's table name
func (*CasinoSession) TableName() string {
	return TableNameCasinoSession
}
