// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "Groups"

// Group mapped from table <Groups>
type Group struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	MsgCounter int32     `gorm:"column:msgCounter;not null" json:"msgCounter"`
	AdsCounter int32     `gorm:"column:adsCounter;not null" json:"adsCounter"`
	CreatedAt  time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
