// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVerificationRequest = "VerificationRequest"

// VerificationRequest mapped from table <VerificationRequest>
type VerificationRequest struct {
	ID                  int32  `gorm:"column:id;primaryKey;default:nextval('"VerificationRequest_id_seq"" json:"id"`
	UserID              string `gorm:"column:userId;not null" json:"userId"`
	Password            string `gorm:"column:password;not null" json:"password"`
	Code                string `gorm:"column:code;not null" json:"code"`
	ExpirationTimestamp int64  `gorm:"column:expirationTimestamp;not null" json:"expirationTimestamp"`
}

// TableName VerificationRequest's table name
func (*VerificationRequest) TableName() string {
	return TableNameVerificationRequest
}
