// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/drizion/wabot-go/database/model"
)

func newAd(db *gorm.DB, opts ...gen.DOOption) ad {
	_ad := ad{}

	_ad.adDo.UseDB(db, opts...)
	_ad.adDo.UseModel(&model.Ad{})

	tableName := _ad.adDo.TableName()
	_ad.ALL = field.NewAsterisk(tableName)
	_ad.ID = field.NewInt32(tableName, "id")
	_ad.Text = field.NewString(tableName, "text")
	_ad.CreatedAt = field.NewTime(tableName, "createdAt")

	_ad.fillFieldMap()

	return _ad
}

type ad struct {
	adDo adDo

	ALL       field.Asterisk
	ID        field.Int32
	Text      field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a ad) Table(newTableName string) *ad {
	a.adDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ad) As(alias string) *ad {
	a.adDo.DO = *(a.adDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ad) updateTableName(table string) *ad {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.Text = field.NewString(table, "text")
	a.CreatedAt = field.NewTime(table, "createdAt")

	a.fillFieldMap()

	return a
}

func (a *ad) WithContext(ctx context.Context) *adDo { return a.adDo.WithContext(ctx) }

func (a ad) TableName() string { return a.adDo.TableName() }

func (a ad) Alias() string { return a.adDo.Alias() }

func (a ad) Columns(cols ...field.Expr) gen.Columns { return a.adDo.Columns(cols...) }

func (a *ad) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ad) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["text"] = a.Text
	a.fieldMap["createdAt"] = a.CreatedAt
}

func (a ad) clone(db *gorm.DB) ad {
	a.adDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ad) replaceDB(db *gorm.DB) ad {
	a.adDo.ReplaceDB(db)
	return a
}

type adDo struct{ gen.DO }

func (a adDo) Debug() *adDo {
	return a.withDO(a.DO.Debug())
}

func (a adDo) WithContext(ctx context.Context) *adDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adDo) ReadDB() *adDo {
	return a.Clauses(dbresolver.Read)
}

func (a adDo) WriteDB() *adDo {
	return a.Clauses(dbresolver.Write)
}

func (a adDo) Session(config *gorm.Session) *adDo {
	return a.withDO(a.DO.Session(config))
}

func (a adDo) Clauses(conds ...clause.Expression) *adDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adDo) Returning(value interface{}, columns ...string) *adDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adDo) Not(conds ...gen.Condition) *adDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adDo) Or(conds ...gen.Condition) *adDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adDo) Select(conds ...field.Expr) *adDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adDo) Where(conds ...gen.Condition) *adDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adDo) Order(conds ...field.Expr) *adDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adDo) Distinct(cols ...field.Expr) *adDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adDo) Omit(cols ...field.Expr) *adDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adDo) Join(table schema.Tabler, on ...field.Expr) *adDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adDo) LeftJoin(table schema.Tabler, on ...field.Expr) *adDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adDo) RightJoin(table schema.Tabler, on ...field.Expr) *adDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adDo) Group(cols ...field.Expr) *adDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adDo) Having(conds ...gen.Condition) *adDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adDo) Limit(limit int) *adDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adDo) Offset(offset int) *adDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *adDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adDo) Unscoped() *adDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adDo) Create(values ...*model.Ad) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adDo) CreateInBatches(values []*model.Ad, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adDo) Save(values ...*model.Ad) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adDo) First() (*model.Ad, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ad), nil
	}
}

func (a adDo) Take() (*model.Ad, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ad), nil
	}
}

func (a adDo) Last() (*model.Ad, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ad), nil
	}
}

func (a adDo) Find() ([]*model.Ad, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ad), err
}

func (a adDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ad, err error) {
	buf := make([]*model.Ad, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adDo) FindInBatches(result *[]*model.Ad, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adDo) Attrs(attrs ...field.AssignExpr) *adDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adDo) Assign(attrs ...field.AssignExpr) *adDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adDo) Joins(fields ...field.RelationField) *adDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adDo) Preload(fields ...field.RelationField) *adDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adDo) FirstOrInit() (*model.Ad, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ad), nil
	}
}

func (a adDo) FirstOrCreate() (*model.Ad, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ad), nil
	}
}

func (a adDo) FindByPage(offset int, limit int) (result []*model.Ad, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adDo) Delete(models ...*model.Ad) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adDo) withDO(do gen.Dao) *adDo {
	a.DO = *do.(*gen.DO)
	return a
}
